{% set version = '0.5-5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sf
  version: {{ version|replace("-", "_") }}

source:
  fn: sf_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/sf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sf/sf_{{ version }}.tar.gz
  sha256: 82ad31f98243b6982302fe245ee6e0d8d0546e5ff213ccc00ec3025dfec62229


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: geosphere (>= 1.5-5), maptools, maps, rgdal, rgeos, sp (>= 1.2-4), raster, RSQLite, RPostgreSQL, tibble, rlang, dplyr (>= 0.7-0), tidyr (>= 0.7-0), ggplot2, mapview, tmap, testthat, knitr, covr, microbenchmark, spatstat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}automake          # [not win]
    - {{posix}}pkg-config
    - {{posix}}make

  host:
    - r-base
    - r-dbi >=0.5
    - r-rcpp
    - r-classint
    - r-magrittr
    - r-units >=0.4_6
    - {{native}}gdal             # [win]
    - {{native}}libgdal          # [unix]
    - {{native}}proj4            # [linux]
    # For some reason, without this, 3.6.0 was getting selected and conflicting with libgdal's geos dep
    - {{native}}geos >=3.6.2,<3.6.3.0a0  # [linux]

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-dbi >=0.5
    - r-rcpp
    - r-classint
    - r-magrittr
    - r-units >=0.4_6

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('sf')"           # [not win]
    - "\"%R%\" -e \"library('sf')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-spatial/sf/
  license: GPL-2 | MIT + file LICENSE
  summary: Support for simple features, a standardized way to encode spatial vector data. Binds  to
    GDAL for reading and writing data, to GEOS for geometrical operations, and to Proj.4
    for projection conversions and datum transformations.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: sf
# Version: 0.5-5
# Title: Simple Features for R
# Description: Support for simple features, a standardized way to encode spatial vector data. Binds  to GDAL for reading and writing data, to GEOS for geometrical operations, and to Proj.4 for projection conversions and datum transformations.
# Authors@R: c(person("Edzer", "Pebesma", role = c("aut", "cre"), email = "edzer.pebesma@uni-muenster.de", comment = c(ORCID = "0000-0001-8049-7069")), person("Roger", "Bivand", role = "ctb", comment = c(ORCID = "0000-0003-2392-6140")), person("Ian", "Cook", role = "ctb"), person("Tim", "Keitt", role = "ctb"), person("Michael", "Sumner", role = "ctb"), person("Robin", "Lovelace", role = "ctb"), person("Hadley", "Wickham", role = "ctb"), person("Jeroen", "Ooms", role = "ctb"), person("Etienne", "Racine", role = "ctb"))
# Depends: R (>= 3.3.0), methods
# Imports: utils, stats, tools, graphics, grDevices, grid, Rcpp, DBI (>= 0.5), units (>= 0.4-6), classInt, magrittr
# Suggests: geosphere (>= 1.5-5), maptools, maps, rgdal, rgeos, sp (>= 1.2-4), raster, RSQLite, RPostgreSQL, tibble, rlang, dplyr (>= 0.7-0), tidyr (>= 0.7-0), ggplot2, mapview, tmap, testthat, knitr, covr, microbenchmark, spatstat
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# SystemRequirements: GDAL (>= 2.0.0), GEOS (>= 3.3.0), PROJ.4 (>= 4.8.0)
# License: GPL-2 | MIT + file LICENSE
# URL: https://github.com/r-spatial/sf/
# BugReports: https://github.com/r-spatial/sf/issues/
# Collate: RcppExports.R init.R crs.R bbox.R read.R db.R sfc.R sfg.R sf.R bind.R wkb.R wkt.R plot.R geom.R transform.R sp.R grid.R arith.R tidyverse.R cast_sfg.R cast_sfc.R graticule.R datasets.R aggregate.R agr.R maps.R join.R sample.R valid.R geohash.R split.R collection_extract.R jitter.R sgbp.R spatstat.R
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-10-31 14:10:14 UTC; edzer
# Author: Edzer Pebesma [aut, cre] (0000-0001-8049-7069), Roger Bivand [ctb] (0000-0003-2392-6140), Ian Cook [ctb], Tim Keitt [ctb], Michael Sumner [ctb], Robin Lovelace [ctb], Hadley Wickham [ctb], Jeroen Ooms [ctb], Etienne Racine [ctb]
# Maintainer: Edzer Pebesma <edzer.pebesma@uni-muenster.de>
# Repository: CRAN
# Date/Publication: 2017-10-31 16:03:27 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
