travis:
  secure:
    BINSTAR_TOKEN: B1tJpTKN0Fg4sdU0EqYCi3VSz4xl5ZdQQ4UugiI9b7m7aPLhUvq3fThYsA16LqpLoyZAPvO+2R54nPLEp7ipjQQZ0/QOUseoBswlVFnoRBICQy2NUUJ9Nu/q1fr7FflAQLHRuaoX7EmldClsnjglX61bXnfgIEcj7ROBobFlrLatOMYWeH6ognTAoQ/krlrkPC44xj3RWI4soJlKY2GLV22edjMBiXNacD73oCFFX+H2gLDnDt3IiAiUqhxE8Vaqxw9/jRb9jFO0gJRZ49VHOrJsiwHAkoF6ba8py0WFEFeJki+x5ySPNRBK0Y/iVVJLEgDcp8IAt7o9pINv/h9pEfP+l1p2KEYyRrs7AIoq4rzR5kZ7hNqVRsshQNjZDTQBiM9X+ZPSRs0P9jRMjKGzebkCAKVcfcROkcwIuceoksSNwcesE0AwNJZOPmB3oxwHtCN6XZ18wauYHPlFRVKfnySRDRyoaI9YyZ5RRupblXQ7bZmOde4H68GMC5oFuZQrgbF44csNX3ATNcmQSsowHDetBOuvrFIwepVmtfLwF020fi5IhE6kvyq4j4BfzR8dVp/D/oR69Qtk3AfOhNLXRj+Cb8viOYcPF4DDXfTsh2bFxm8EJbwtwhQW8/gdcH9LLwr/76CgNl8X6RNfwUHZoajJwl/JXpg3oKGfPMNBEHs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
