travis:
  secure:
    BINSTAR_TOKEN: orOctmU/yMt5K5ZmXPxQzBms0N38cIXXuDKbBys7YHdcceoD6AO/Oh/AeshK6x0KXc8fqhH4YOpukgy8F0EPdstG7SsyfYAhFQdyZO3nKVmYoZqXmnA7ufkWpkkgPKxudJHMmlGXkXSKJ5OQ3k/0sZ/tX8rAB/FncfrSOi3B+V4hlCf6G6c4uOadL4ARWI6AOsSKsY5wIHlPXzIZmdDZXfmHZvyrsX6rNq0ljyMX742oVY1d1PzQDglcHM67bzaBMYU/QEQK+iiT/11sScwa0gpQu6SzykL1tM5DhFdmD4gBX7jhdBTeDsExCXUvPgDCh7Jq8A2y0TaPiu0H/ePg8L4fy95vwyDNASq0NTWCKL44UYJLdnTwgXtKZSGabHzpeAjclu5Dz6ONTw6C2ZA3KTLE9vQF2DhxkBsq2TTd/L+M5uFUgnv1Yc6ZQCmQgDp+a6t4UXC/YdG8yFVuB5qtWM87nEb/GtM+CuZEsuC72ta2zcV9mXBOHiMCx2kUP/FjBwfJEMW+uHctb34hTkTsLLerl4PNhQFuF6G9uQJRCLEs0lFlQNfIsJPf7RkgAfXboc8yX0vWK2R3k/wvJl7uGxWxUCGbL/rSzlInWwPpoPC3KSuPh59KCBg3GON70YqjjJ8MBSJI2tPvlfrVZW3rK8jSdgDOr8D6akCeiky58aQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
